#!/usr/bin/env bash
set -euo pipefail

multipowers_faq_root() {
  echo "${PROJECT_ROOT:-$PWD}/.multipowers"
}

faq_events_file() {
  echo "$(multipowers_faq_root)/temp/events/failures.ndjson"
}

faq_output_file() {
  echo "$(multipowers_faq_root)/FAQ.md"
}

classify_error_type() {
  local raw="${1:-unknown}"
  local msg="${2:-}"
  local s="${raw} ${msg}"
  s="$(echo "$s" | tr '[:upper:]' '[:lower:]')"
  case "$s" in
    *proxy*|*connect*|*network*|*dns*|*tls*) echo "proxy-network" ;;
    *timeout*|*timed*|*deadline*) echo "timeout" ;;
    *auth*|*permission*|*unauthorized*|*forbidden*|*token*) echo "auth-permission" ;;
    *context*|*missing*|*init*|*not\ found*) echo "missing-context" ;;
    *model*unavailable*|*unknown\ model*|*no\ capacity*) echo "model-unavailable" ;;
    *path*|*workspace*|*outside*|*boundary*) echo "path-boundary" ;;
    *capacity*|*resource_exhausted*|*quota*) echo "provider-capacity" ;;
    *pre-run*|*prerun*|*runtime.json*) echo "runtime-prerun" ;;
    *) echo "missing-context" ;;
  esac
}

record_failure_event() {
  local command_name="${1:-unknown}"
  local phase="${2:-unknown}"
  local provider="${3:-none}"
  local error_hint="${4:-failure}"
  local root_cause="${5:-unknown}"
  local suggested_fix="${6:-Check logs and retry.}"
  local exit_code="${7:-1}"

  local croot events ftype now
  croot="$(multipowers_faq_root)"
  events="$(faq_events_file)"
  mkdir -p "$(dirname "$events")"

  ftype="$(classify_error_type "$error_hint" "$root_cause")"
  now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  python3 - "$events" "$now" "$command_name" "$phase" "$provider" "$ftype" "$error_hint" "$root_cause" "$suggested_fix" "$exit_code" <<'PY'
import json
import os
import sys

path, ts, cmd, phase, provider, etype, hint, root, fix, code = sys.argv[1:]
os.makedirs(os.path.dirname(path), exist_ok=True)
obj = {
    "timestamp": ts,
    "command": cmd,
    "phase": phase,
    "provider": provider,
    "error_type": etype,
    "error_hint": hint,
    "root_cause": root,
    "suggested_fix": fix,
    "exit_code": int(code) if str(code).isdigit() else code,
}
with open(path, "a", encoding="utf-8") as f:
    f.write(json.dumps(obj, ensure_ascii=False) + "\n")
PY

  regenerate_faq_from_events || true
}

regenerate_faq_from_events() {
  local events faq
  events="$(faq_events_file)"
  faq="$(faq_output_file)"
  [[ -f "$events" ]] || return 0

  python3 - "$events" "$faq" <<'PY'
import collections
import json
import os
import re
import sys
from datetime import datetime

src, dst = sys.argv[1:]

buckets = collections.defaultdict(dict)
order = [
    "proxy-network",
    "timeout",
    "auth-permission",
    "missing-context",
    "model-unavailable",
    "path-boundary",
    "provider-capacity",
    "runtime-prerun",
]

def norm(s: str) -> str:
    s = (s or "").strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s

with open(src, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        try:
            e = json.loads(line)
        except Exception:
            continue
        etype = e.get("error_type") or "missing-context"
        if etype not in order:
            etype = "missing-context"
        root = norm(e.get("root_cause", "unknown"))
        fix = norm(e.get("suggested_fix", "check logs and retry"))
        key = f"{etype}|{root}|{fix}"
        existing = buckets[etype].get(key)
        ts = e.get("timestamp") or datetime.utcnow().isoformat() + "Z"
        cmd = e.get("command") or "unknown"
        if existing is None:
            buckets[etype][key] = {
                "count": 1,
                "last_seen": ts,
                "commands": {cmd},
                "root_cause": e.get("root_cause", "unknown"),
                "suggested_fix": e.get("suggested_fix", "check logs and retry"),
            }
        else:
            existing["count"] += 1
            if ts >= existing["last_seen"]:
                existing["last_seen"] = ts
            existing["commands"].add(cmd)

entries = []
for etype in order:
    for item in buckets[etype].values():
        entries.append((etype, item))

# Limit to top 120 by count then recency
entries.sort(key=lambda x: (x[1]["count"], x[1]["last_seen"]), reverse=True)
entries = entries[:120]

limited = collections.defaultdict(list)
for etype, item in entries:
    limited[etype].append(item)

os.makedirs(os.path.dirname(dst), exist_ok=True)
with open(dst, "w", encoding="utf-8") as out:
    out.write("# Multipowers FAQ (Auto-Generated)\n\n")
    out.write("This file is automatically generated and refined.\n")
    out.write("Do not manually edit unless debugging the generator.\n\n")
    for etype in order:
        out.write(f"## {etype}\n")
        section = limited.get(etype, [])
        if not section:
            out.write("_No entries yet._\n\n")
            continue
        for idx, item in enumerate(section, start=1):
            cmds = ", ".join(sorted(item["commands"]))
            out.write(f"### {idx}. {item['root_cause']}\n")
            out.write(f"- Fix: {item['suggested_fix']}\n")
            out.write(f"- Seen: {item['count']}\n")
            out.write(f"- Last seen: {item['last_seen']}\n")
            out.write(f"- Commands: {cmds}\n\n")
PY
}
